# Generated by Django 4.2 on 2023-04-08 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='isCompleted',
            new_name='is_completed',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
        migrations.AddField(
            model_name='todo',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='TodoItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('iscompleted', models.BooleanField(default=False)),
                ('todo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.todo')),
            ],
        ),
    ]
