# Generated by Django 4.2 on 2023-04-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_iscompleted_todo_is_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitems',
            old_name='Description',
            new_name='task',
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
